version: '3.8'
services:
  redis:
    restart: unless-stopped
    image: redis:7-alpine
    networks:
      - balloony-net

  app:
    restart: unless-stopped
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./tilecache:/app/tilecache
    environment:
      REDIS_ADDR: redis:6379
    networks:
      - balloony-net

networks:
  balloony-net:
    driver: bridge
